backend:
  name: git-gateway
  branch: main

site_url: "https://stellar-capybara-bc6320.netlify.app"

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Homepage (index.html)"
        name: "home"
        fields:
          - { label: "Raw HTML", name: "body", widget: "text" }
